// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptiFuel.Data;

#nullable disable

namespace OptiFuel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240725152200_V4")]
    partial class V4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OptiFuel.Models.Centre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("e_created_on")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("e_updated_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("centres");
                });

            modelBuilder.Entity("OptiFuel.Models.Comission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ValidationBLId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("e_created_on")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("e_updated_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Comissions");
                });

            modelBuilder.Entity("OptiFuel.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Télephone")
                        .HasColumnType("int");

                    b.Property<DateTime>("e_created_on")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("e_updated_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("OptiFuel.Models.Dechargement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cuve")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryVolume")
                        .HasColumnType("int");

                    b.Property<int>("LevelEnd")
                        .HasColumnType("int");

                    b.Property<int>("LevelStart")
                        .HasColumnType("int");

                    b.Property<Guid>("ValidationBLId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("e_created_on")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("e_updated_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Dechargements");
                });

            modelBuilder.Entity("OptiFuel.Models.Planning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Center")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantiteALivrer")
                        .HasColumnType("int");

                    b.Property<DateTime>("e_created_on")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("e_updated_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Planings");
                });

            modelBuilder.Entity("OptiFuel.Models.ValidationBL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("BLFile")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("CertificatJumelageFile")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanningId")
                        .HasColumnType("int");

                    b.Property<int>("QuantitésBL")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("e_created_on")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("e_updated_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlanningId")
                        .IsUnique();

                    b.ToTable("validationBLs");
                });

            modelBuilder.Entity("OptiFuel.Models.ValidationBL", b =>
                {
                    b.HasOne("OptiFuel.Models.Planning", "Planning")
                        .WithOne("ValidationBLs")
                        .HasForeignKey("OptiFuel.Models.ValidationBL", "PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("OptiFuel.Models.Planning", b =>
                {
                    b.Navigation("ValidationBLs");
                });
#pragma warning restore 612, 618
        }
    }
}
